import Link from 'next/link';

import { Header, Footer } from '@/components/landing';
import { CodeBlock } from '@/components/docs/CodeBlock';
import { ConfigTable, type ConfigEntry } from '@/components/docs/ConfigTable';
import { MermaidDiagram } from '@/components/docs/MermaidDiagram';

const features = [
  {
    title: 'In-process execution',
    description: 'Runs entirely inside a FastAPI process without external sandboxing.',
  },
  {
    title: 'Tool-rich agent',
    description: 'Image, video, audio, TTS, deep research, and code execution tools are built in.',
  },
  {
    title: 'Vision routing',
    description: 'Image requests route to dedicated vision models before tool execution.',
  },
  {
    title: 'Streaming responses',
    description: 'SSE streaming delivers reasoning content, artifacts, and final responses.',
  },
  {
    title: 'Extensible tool system',
    description: 'Add or replace tools via LangChain tool bindings.',
  },
  {
    title: 'Fast path fallback',
    description: 'Simple prompts go directly to ChatOpenAI for speed and cost control.',
  },
];

const howItWorksSteps = [
  'Receives OpenAI-compatible chat completion requests.',
  'Runs a vision check to identify image workloads.',
  'Uses keyword and LLM verification to decide fast path vs agent path.',
  'Executes LangChain agents and tools in-process.',
  'Streams SSE responses with reasoning content and artifacts.',
];

const configSections: Array<{ title: string; description?: string; entries: ConfigEntry[] }> = [
  {
    title: 'Server configuration',
    entries: [
      {
        name: 'BASELINE_LANGCHAIN_HOST',
        defaultValue: '0.0.0.0',
        description: 'Server host binding for the API.',
      },
      {
        name: 'BASELINE_LANGCHAIN_PORT',
        defaultValue: '8080',
        description: 'Server port for the API.',
      },
      {
        name: 'BASELINE_LANGCHAIN_DEBUG',
        defaultValue: 'false',
        description: 'Enable debug logging and verbose output.',
      },
    ],
  },
  {
    title: 'Model configuration',
    entries: [
      {
        name: 'BASELINE_LANGCHAIN_MODEL',
        defaultValue: 'gpt-4o-mini',
        description: 'Primary LLM model used by the agent and fast path.',
      },
      {
        name: 'BASELINE_LANGCHAIN_OPENAI_API_KEY',
        defaultValue: '-',
        description: 'OpenAI-compatible API key for the main LLM.',
      },
      {
        name: 'BASELINE_LANGCHAIN_OPENAI_BASE_URL',
        defaultValue: 'https://api.openai.com/v1',
        description: 'OpenAI-compatible base URL for the main LLM.',
      },
      {
        name: 'BASELINE_LANGCHAIN_CHUTES_API_KEY',
        defaultValue: '-',
        description: 'Chutes API key for image and TTS tools.',
      },
      {
        name: 'BASELINE_LANGCHAIN_CHUTES_API_BASE',
        defaultValue: 'https://llm.chutes.ai/v1',
        description: 'Chutes API base URL for tool calls.',
      },
    ],
  },
  {
    title: 'Search and research',
    entries: [
      {
        name: 'BASELINE_LANGCHAIN_TAVILY_API_KEY',
        defaultValue: '-',
        description: 'Tavily API key for web search.',
      },
      {
        name: 'BASELINE_LANGCHAIN_CHUTES_SEARCH_URL',
        defaultValue: 'https://chutes-search.onrender.com',
        description: 'Chutes search base URL for deep research.',
      },
    ],
  },
  {
    title: 'Vision routing',
    entries: [
      {
        name: 'BASELINE_LANGCHAIN_VISION_MODEL_PRIMARY',
        defaultValue: 'Qwen/Qwen3-VL-235B-A22B-Instruct',
        description: 'Primary vision model for image requests.',
      },
      {
        name: 'BASELINE_LANGCHAIN_VISION_MODEL_FALLBACK',
        defaultValue: 'chutesai/Mistral-Small-3.2-24B-Instruct-2506',
        description: 'Fallback vision model for image requests.',
      },
      {
        name: 'BASELINE_LANGCHAIN_VISION_MODEL_TIMEOUT',
        defaultValue: '60.0',
        description: 'Timeout for vision model requests (seconds).',
      },
      {
        name: 'BASELINE_LANGCHAIN_ENABLE_VISION_ROUTING',
        defaultValue: 'true',
        description: 'Route image requests to vision models.',
      },
    ],
  },
  {
    title: 'Artifacts',
    entries: [
      {
        name: 'BASELINE_LANGCHAIN_ARTIFACTS_DIR',
        defaultValue: '/tmp/janus_baseline_langchain_artifacts',
        description: 'Local path for artifacts generated by the agent.',
      },
      {
        name: 'BASELINE_LANGCHAIN_ARTIFACT_BASE_URL',
        defaultValue: '/artifacts',
        description: 'Base URL for served artifacts.',
      },
    ],
  },
  {
    title: 'Routing controls',
    entries: [
      {
        name: 'BASELINE_LANGCHAIN_COMPLEXITY_THRESHOLD',
        defaultValue: '100',
        description: 'Token threshold for complexity detection.',
      },
      {
        name: 'BASELINE_LANGCHAIN_ALWAYS_USE_AGENT',
        defaultValue: 'false',
        description: 'Force all requests onto the agent path.',
      },
    ],
  },
  {
    title: 'Container overrides',
    description: 'Alternative environment variables honored by container deployments.',
    entries: [
      {
        name: 'HOST',
        defaultValue: '-',
        description: 'Container host override.',
      },
      {
        name: 'PORT',
        defaultValue: '-',
        description: 'Container port override.',
      },
      {
        name: 'DEBUG',
        defaultValue: '-',
        description: 'Container debug override.',
      },
      {
        name: 'LOG_LEVEL',
        defaultValue: '-',
        description: 'Container log level override.',
      },
      {
        name: 'OPENAI_API_KEY',
        defaultValue: '-',
        description: 'Container OpenAI API key alias.',
      },
      {
        name: 'OPENAI_BASE_URL',
        defaultValue: '-',
        description: 'Container OpenAI base URL alias.',
      },
      {
        name: 'CHUTES_API_KEY',
        defaultValue: '-',
        description: 'Container Chutes API key alias.',
      },
      {
        name: 'TAVILY_API_KEY',
        defaultValue: '-',
        description: 'Container Tavily API key alias.',
      },
    ],
  },
];

const gettingStartedCode = `cd baseline-langchain
python -m venv .venv
source .venv/bin/activate
pip install -e ".[dev]"
python -m janus_baseline_langchain.main`;

const exampleRequest = `curl -N -X POST http://localhost:8080/v1/chat/completions \\
  -H "Content-Type: application/json" \\
  -d '{"model": "baseline-langchain", "messages": [{"role": "user", "content": "Generate an image of a cat"}], "stream": true}'`;

const langchainDiagram = `flowchart TB
    subgraph Request ["Incoming Request"]
        REQ["POST /v1/chat/completions"]
    end

    subgraph Routing ["Complexity Detection"]
        DETECT["Complexity Detector"]
        KEYWORDS["Keyword Check"]
        LLM_VERIFY["LLM Verification"]
    end

    subgraph FastPath ["Fast Path"]
        DIRECT_LLM["Direct ChatOpenAI"]
        FAST_STREAM["Stream Response"]
    end

    subgraph AgentPath ["Agent Path"]
        AGENT["LangChain Agent"]
        TOOLS["Available Tools"]
    end

    subgraph Tools ["Agent Capabilities"]
        IMG["Image Generation"]
        VIDEO["Video Generation"]
        AUDIO["Audio Generation"]
        TTS["Text-to-Speech"]
        SEARCH["Web Search"]
        RESEARCH["Deep Research"]
        CODE["Code Execution"]
        FILES["File Operations"]
    end

    subgraph Response ["Response"]
        SSE["SSE Stream"]
        REASONING["reasoning_content"]
        CONTENT["content"]
        ARTIFACTS["artifacts"]
    end

    REQ --> DETECT
    DETECT --> KEYWORDS
    KEYWORDS -->|"Complex"| AGENT
    KEYWORDS -->|"Simple"| LLM_VERIFY
    LLM_VERIFY -->|"needs_agent: true"| AGENT
    LLM_VERIFY -->|"needs_agent: false"| DIRECT_LLM
    LLM_VERIFY -->|"Error"| AGENT

    DIRECT_LLM --> FAST_STREAM
    FAST_STREAM --> SSE

    AGENT --> TOOLS
    TOOLS --> IMG
    TOOLS --> VIDEO
    TOOLS --> AUDIO
    TOOLS --> TTS
    TOOLS --> SEARCH
    TOOLS --> RESEARCH
    TOOLS --> CODE
    TOOLS --> FILES
    AGENT --> SSE

    SSE --> REASONING
    SSE --> CONTENT
    SSE --> ARTIFACTS`;

export default function BaselineLangChainPage() {
  return (
    <div className="min-h-screen aurora-bg flex flex-col">
      <Header />
      <main className="flex-1 py-16 lg:py-24">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
          <div>
            <Link
              href="/competition"
              className="text-[#63D297] hover:underline inline-flex items-center gap-2"
            >
              <svg
                className="w-4 h-4"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.6"
              >
                <path d="M19 12H5" />
                <path d="M11 6l-6 6 6 6" />
              </svg>
              Back to Competition
            </Link>
          </div>

          <header className="space-y-4">
            <h1 className="text-3xl sm:text-4xl font-semibold text-[#F3F4F6]">
              LangChain Baseline
            </h1>
            <p className="text-lg text-[#9CA3AF]">
              In-process reference implementation using LangChain agents with direct tool
              integration and streaming support.
            </p>
          </header>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#F3F4F6]">Architecture</h2>
            <MermaidDiagram
              chart={langchainDiagram}
              ariaLabel="LangChain baseline architecture"
            />
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#F3F4F6]">How It Works</h2>
            <ol className="space-y-3 text-sm text-[#D1D5DB] list-decimal list-inside">
              {howItWorksSteps.map((step) => (
                <li key={step}>{step}</li>
              ))}
            </ol>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#F3F4F6]">Request Flow</h2>
            <p className="text-sm text-[#9CA3AF]">
              LangChain uses the same OpenAI-compatible payloads and streams results over SSE.
            </p>
            <CodeBlock language="bash">{exampleRequest}</CodeBlock>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#F3F4F6]">Features</h2>
            <div className="grid sm:grid-cols-2 gap-4">
              {features.map((feature) => (
                <FeatureCard key={feature.title} {...feature} />
              ))}
            </div>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl font-semibold text-[#F3F4F6]">Configuration</h2>
            <div className="space-y-6">
              {configSections.map((section) => (
                <ConfigTable
                  key={section.title}
                  title={section.title}
                  description={section.description}
                  entries={section.entries}
                />
              ))}
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#F3F4F6]">Getting Started</h2>
            <CodeBlock language="bash" title="Local setup">
              {gettingStartedCode}
            </CodeBlock>
          </section>

          <div className="flex justify-center">
            <a
              href="https://github.com/fstandhartinger/janus-poc/tree/main/baseline-langchain"
              target="_blank"
              rel="noreferrer"
              className="btn-primary inline-flex items-center gap-2"
            >
              <GithubIcon className="w-4 h-4" />
              View on GitHub
            </a>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}

function FeatureCard({ title, description }: { title: string; description: string }) {
  return (
    <div className="glass-card p-4 space-y-2">
      <h3 className="text-lg font-semibold text-[#F3F4F6]">{title}</h3>
      <p className="text-sm text-[#9CA3AF]">{description}</p>
    </div>
  );
}

function GithubIcon({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="currentColor"
      aria-hidden="true"
    >
      <path d="M12 2C6.48 2 2 6.58 2 12.26c0 4.5 2.87 8.31 6.84 9.66.5.1.68-.22.68-.49 0-.24-.01-.87-.01-1.7-2.78.62-3.37-1.38-3.37-1.38-.46-1.2-1.11-1.52-1.11-1.52-.9-.64.07-.63.07-.63 1 .07 1.53 1.05 1.53 1.05.9 1.57 2.36 1.12 2.94.86.09-.67.35-1.12.63-1.38-2.22-.26-4.56-1.14-4.56-5.08 0-1.12.39-2.03 1.03-2.75-.1-.26-.45-1.3.1-2.7 0 0 .84-.27 2.75 1.03.8-.23 1.66-.35 2.52-.35.86 0 1.72.12 2.52.35 1.9-1.3 2.74-1.03 2.74-1.03.55 1.4.2 2.44.1 2.7.64.72 1.03 1.63 1.03 2.75 0 3.95-2.35 4.81-4.58 5.06.36.32.68.94.68 1.9 0 1.37-.01 2.47-.01 2.8 0 .27.18.6.69.49 3.96-1.35 6.82-5.16 6.82-9.66C22 6.58 17.52 2 12 2z" />
    </svg>
  );
}
