"""Pydantic models for the baseline competitor."""

from .openai import (
    AssistantMessage,
    ChatCompletionRequest,
    ChatCompletionResponse,
    ChatCompletionChunk,
    GenerationFlags,
    Message,
    MessageContent,
    MessageRole,
    TextContent,
    ImageUrl,
    ImageUrlContent,
    Choice,
    ChunkChoice,
    Delta,
    Usage,
    FinishReason,
    FunctionDefinition,
    ToolDefinition,
    FunctionCall,
    ToolCall,
    Artifact,
    ArtifactType,
)
from .debug import DebugEvent, DebugEventType
from .utils import extract_images, extract_text_content

__all__ = [
    "AssistantMessage",
    "ChatCompletionRequest",
    "ChatCompletionResponse",
    "ChatCompletionChunk",
    "GenerationFlags",
    "Message",
    "MessageContent",
    "MessageRole",
    "TextContent",
    "ImageUrl",
    "ImageUrlContent",
    "Choice",
    "ChunkChoice",
    "Delta",
    "Usage",
    "FinishReason",
    "FunctionDefinition",
    "ToolDefinition",
    "FunctionCall",
    "ToolCall",
    "Artifact",
    "ArtifactType",
    "DebugEvent",
    "DebugEventType",
    "extract_images",
    "extract_text_content",
]
