"""Pydantic models for OpenAI API compatibility and Janus extensions."""

from .openai import (
    ChatCompletionRequest,
    ChatCompletionResponse,
    ChatCompletionChunk,
    Message,
    MessageContent,
    MessageRole,
    TextContent,
    ImageUrlContent,
    FileContent,
    FileInfo,
    Choice,
    ChunkChoice,
    Delta,
    Usage,
    FinishReason,
    ToolCall,
    FunctionCall,
    Tool,
    FunctionDefinition,
    ResponseFormat,
    StreamOptions,
)
from .janus import (
    Artifact,
    ArtifactType,
    JanusEvent,
    JanusEventType,
    CompetitorInfo,
    HealthResponse,
    ModelInfo,
    ModelsResponse,
)
from .streaming import ScreenshotEvent, format_screenshot_sse

__all__ = [
    # OpenAI models
    "ChatCompletionRequest",
    "ChatCompletionResponse",
    "ChatCompletionChunk",
    "Message",
    "MessageContent",
    "MessageRole",
    "TextContent",
    "ImageUrlContent",
    "FileContent",
    "FileInfo",
    "Choice",
    "ChunkChoice",
    "Delta",
    "Usage",
    "FinishReason",
    "ToolCall",
    "FunctionCall",
    "Tool",
    "FunctionDefinition",
    "ResponseFormat",
    "StreamOptions",
    # Janus models
    "Artifact",
    "ArtifactType",
    "JanusEvent",
    "JanusEventType",
    "CompetitorInfo",
    "HealthResponse",
    "ModelInfo",
    "ModelsResponse",
    "ScreenshotEvent",
    "format_screenshot_sse",
]
